const images = {
  back: require("../../assets/images/back.png"),
  close: require("../../assets/images/close.png"),
  bank1: require("../../assets/images/bank1.png"),
  bank2: require("../../assets/images/bank2.png"),
  contact: require("../../assets/images/contact.png"),
  cover1: require("../../assets/images/cover1.png"),
  cover2: require("../../assets/images/cover2.png"),
  cover3: require("../../assets/images/cover3.png"),
  dots: require("../../assets/images/dots.png"),
  favicon: require("../../assets/images/favicon.png"),
  goldCard: require("../../assets/images/goldCard.png"),
  goldCard_vertical: require("../../assets/images/goldCard_vertical.png"),
  home: require("../../assets/images/home.png"),
  icon: require("../../assets/images/icon.png"),
  menu: require("../../assets/images/menu.png"),
  notification: require("../../assets/images/notif.png"),
  platinumCard_vertical: require("../../assets/images/platinumCard_vertical.png"),
  preview1: require("../../assets/images/preview1.png"),
  preview2: require("../../assets/images/preview2.png"),
  profile: require("../../assets/images/profile.png"),
  profile_cover: require("../../assets/images/profile_cover.png"),
  profile_nocover: require("../../assets/images/profile_nocover.png"),
  search: require("../../assets/images/search.png"),
  signup_logo: require("../../assets/images/signup_logo.png"),
  silverCard_vertical: require("../../assets/images/silverCard_vertical.png"),
  splash: require("../../assets/images/splash.png"),
  transfer: require("../../assets/images/transfer.png"),
  vote: require("../../assets/images/vote.png"),
};

export default images;
